using System.Collections.Generic;

record Token(string Type, string Value, int Line, int Column);
record VarInfo(string Type, string Value, bool IsConst = false, bool IsRuntime = false);
record ExprResult(string Type, string Value, string Repr);
record FileValue(string Kind, string Value);
record CompareResult(bool Value, string Repr);
record RuntimeAction(string Op, string Path, string ValueKind, string Value, string Target);
record StyleProperty(string Target, string State, string Property, string ValueKind, string Value, string Unit, string Source);
record StylePresetProperty(string Name, string Property, string ValueKind, string Value, string Unit, string Source);
record StyleApplication(string StyleName, string Target, string State);
record UiObject(string Type, string Name);
record UiProperty(string Target, string Property, string ValueKind, string Value, string Source);
record UiLayoutProperty(string Target, string Property, string ValueKind, string Value, string Unit, string Source);
record UiParent(string Child, string Parent);
record UiDock(string Target, string Side, string Parent);
record UiEvent(string Event, string Target, string TargetKind, int BodyLineCount);
record UiBinding(string Target, string Property, string Source, string SourceType);
record UiState(string Target, string Property, string ValueKind, string Value);
record UiResource(string Type, string Name, string Path);
record UiResourceUse(string Target, string Property, string ResourceName, string ResourceType);
record Dx12Renderer(string Name);
record Dx12RendererParent(string Renderer, string Window);
record Dx12RendererClearStyle(string Renderer, string State, string ValueKind, string Value, string Unit, string Source);
record Dx12RendererClearReady(string Renderer, string Window, string ValueKind, string Value, string Unit, string Source);
record Dx12FrameCommand(string Command, string Renderer);
record Dx12Shader(string Name, string VertexSource, string PixelSource);
record Dx12Pipeline(string Name, string Renderer, string Shader, string Topology);
record Dx12PipelineBind(string Pipeline, string Renderer);
record Dx12VertexBuffer(string Name);
record Dx12Vertex(string Buffer, int Index, string Position, string Color);
record Dx12VertexBufferBind(string Buffer, string Renderer);
record Dx12Draw(string Renderer, int Vertices, string Buffer, string Pipeline);
record Dx12Object(string Name);
record Dx12ObjectPrimitive(string Object, string Kind);
record Dx12ObjectBinding(string Object, string Renderer, string Pipeline, string VertexBuffer, int Vertices);
record Dx12DrawObject(string Object, string Renderer, int Vertices, string Buffer, string Pipeline);
record Dx12ObjectTransform(string Object, string Property, string Value);
record Dx12Camera(string Name);
record Dx12CameraUse(string Camera, string Renderer);
record Dx12CameraProjection(string Camera, string Projection);
record Dx12CameraTransform(string Camera, string Property, string Value);
record Dx12KeyBinding(string Key, string Action, string Target, string Delta);
record Dx12MouseCapture(string Window);
record Dx12MouseMoveBinding(string Target, string Sensitivity);
record Dx12MouseButtonBinding(string Button, string Action, string Target, string Delta);
record Dx12MouseWheelBinding(string Action, string Target, string Delta);
record Dx12ObjectSelector(string Name);
record Dx12ObjectSelectorUse(string Selector, string Renderer);
record Dx12ObjectSelectionBinding(string Button, string Selector);
record Dx12SelectedObjectRotateBinding(string Key, string Axis, string MouseAxis, string Sensitivity);
record Dx12DirectionalLight(string Name);
record Dx12LightUse(string Light, string Renderer);
record Dx12LightProperty(string Light, string Property, string Value);
record Dx12ConstantBuffer(string Name, string Field, string FieldType, string Value);
record Dx12ConstantBufferBind(string Buffer, string Pipeline);
record Dx12ColorSequence(string Name);
record Dx12ColorKey(string Sequence, int Index, string Value);
record Dx12AnimateColor(string Target, string Buffer, string Field, string Sequence, int EveryFrames);
record AstModel(string Program, List<(string Name, string Type, string Value)> Vars, string Title, string TitleExpr, string TitleCommand, string Message, string MessageExpr, string MessageCommand, int ExitCode, string FinalCommand, List<string> Flow, List<RuntimeAction> RuntimeActions, List<StyleProperty> Styles, List<StylePresetProperty> StylePresets, List<StyleApplication> StyleApplications, List<UiObject> UiObjects, List<UiProperty> UiProperties, List<UiLayoutProperty> UiLayoutProperties, List<UiParent> UiParents, List<UiDock> UiDocks, List<UiEvent> UiEvents, List<UiBinding> UiBindings, List<UiState> UiStates, List<UiResource> UiResources, List<UiResourceUse> UiResourceUses, List<Dx12Renderer> Dx12Renderers, List<Dx12RendererParent> Dx12RendererParents, List<Dx12RendererClearStyle> Dx12RendererClearStyles, List<Dx12RendererClearReady> Dx12RendererClearReadies, List<Dx12FrameCommand> Dx12FrameCommands, List<Dx12Shader> Dx12Shaders, List<Dx12Pipeline> Dx12Pipelines, List<Dx12PipelineBind> Dx12PipelineBinds, List<Dx12VertexBuffer> Dx12VertexBuffers, List<Dx12Vertex> Dx12Vertices, List<Dx12VertexBufferBind> Dx12VertexBufferBinds, List<Dx12Draw> Dx12Draws, List<Dx12Object> Dx12Objects, List<Dx12ObjectBinding> Dx12ObjectBindings, List<Dx12DrawObject> Dx12DrawObjects, List<Dx12ObjectTransform> Dx12ObjectTransforms, List<Dx12ObjectPrimitive> Dx12ObjectPrimitives, List<Dx12Camera> Dx12Cameras, List<Dx12CameraUse> Dx12CameraUses, List<Dx12CameraProjection> Dx12CameraProjections, List<Dx12CameraTransform> Dx12CameraTransforms, List<Dx12KeyBinding> Dx12KeyBindings, List<Dx12MouseCapture> Dx12MouseCaptures, List<Dx12MouseMoveBinding> Dx12MouseMoveBindings, List<Dx12MouseButtonBinding> Dx12MouseButtonBindings, List<Dx12MouseWheelBinding> Dx12MouseWheelBindings, List<Dx12ObjectSelector> Dx12ObjectSelectors, List<Dx12ObjectSelectorUse> Dx12ObjectSelectorUses, List<Dx12ObjectSelectionBinding> Dx12ObjectSelectionBindings, List<Dx12SelectedObjectRotateBinding> Dx12SelectedObjectRotateBindings, List<Dx12DirectionalLight> Dx12DirectionalLights, List<Dx12LightUse> Dx12LightUses, List<Dx12LightProperty> Dx12LightProperties, List<Dx12ConstantBuffer> Dx12ConstantBuffers, List<Dx12ConstantBufferBind> Dx12ConstantBufferBinds, List<Dx12ColorSequence> Dx12ColorSequences, List<Dx12ColorKey> Dx12ColorKeys, List<Dx12AnimateColor> Dx12AnimateColors);
