using System.Collections.Generic;

record Token(string Type, string Value, int Line, int Column);
record VarInfo(string Type, string Value, bool IsConst = false, bool IsRuntime = false);
record ExprResult(string Type, string Value, string Repr);
record FileValue(string Kind, string Value);
record CompareResult(bool Value, string Repr);
record RuntimeAction(string Op, string Path, string ValueKind, string Value, string Target);
record StyleProperty(string Target, string State, string Property, string ValueKind, string Value, string Unit, string Source);
record StylePresetProperty(string Name, string Property, string ValueKind, string Value, string Unit, string Source);
record StyleApplication(string StyleName, string Target, string State);
record UiObject(string Type, string Name);
record UiProperty(string Target, string Property, string ValueKind, string Value, string Source);
record UiLayoutProperty(string Target, string Property, string ValueKind, string Value, string Unit, string Source);
record UiParent(string Child, string Parent);
record UiDock(string Target, string Side, string Parent);
record UiEvent(string Event, string Target, string TargetKind, int BodyLineCount);
record UiBinding(string Target, string Property, string Source, string SourceType);
record UiState(string Target, string Property, string ValueKind, string Value);
record UiResource(string Type, string Name, string Path);
record UiResourceUse(string Target, string Property, string ResourceName, string ResourceType);
record AstModel(string Program, List<(string Name, string Type, string Value)> Vars, string Title, string TitleExpr, string TitleCommand, string Message, string MessageExpr, string MessageCommand, int ExitCode, string FinalCommand, List<string> Flow, List<RuntimeAction> RuntimeActions, List<StyleProperty> Styles, List<StylePresetProperty> StylePresets, List<StyleApplication> StyleApplications, List<UiObject> UiObjects, List<UiProperty> UiProperties, List<UiLayoutProperty> UiLayoutProperties, List<UiParent> UiParents, List<UiDock> UiDocks, List<UiEvent> UiEvents, List<UiBinding> UiBindings, List<UiState> UiStates, List<UiResource> UiResources, List<UiResourceUse> UiResourceUses);
